mode: rule
ipv6: false
mixed-port: 20112
allow-lan: false
log-level: silent
interface-name: ""
port: 0
socks-port: 0
secret: ID_uhy8iusq
external-controller: 127.0.0.1:20113
external-ui: ""
keep-alive-interval: 30
find-process-mode: strict
external-controller-tls: ""
external-ui-name: ""
external-ui-url: ""
unified-delay: true
tcp-concurrent: true
authentication: []
skip-auth-prefixes:
  - 127.0.0.1/8
  - ::1/128
tls:
  certificate: ""
  private-key: ""
global-client-fingerprint: chrome
geodata-mode: false
geo-auto-update: false
geo-update-interval: 24
geodata-loader: standard
geosite-matcher: mph
geox-url:
  geoip: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat
  geosite: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat
  mmdb: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb
  asn: https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb
global-ua: chrome
profile:
  store-selected: true
  store-fake-ip: true
lan-allowed-ips:
  - 0.0.0.0/0
  - ::/0
lan-disallowed-ips: []
tun:
  enable: false
  stack: Mixed
  auto-route: true
  route-address: []
  auto-detect-interface: true
  dns-hijack:
    - any:53
  device: ""
  mtu: 9000
  strict-route: true
  endpoint-independent-nat: false
dns:
  enable: true
  ipv6: false
  use-hosts: false
  use-system-hosts: true
  nameserver:
    - tls://8.8.8.8#ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query#ğŸ¯ å…¨çƒç›´è¿
  nameserver-policy:
    rule-set:GEOSITE-CN: https://223.5.5.5/dns-query#ğŸ¯ å…¨çƒç›´è¿
    rule-set:geolocation-!cn: tls://8.8.8.8#ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  enhanced-mode: redir-host
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
  prefer-h3: false
hosts: {}
proxy-providers: {}
rule-providers:
  category-ads-all:
    type: http
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/category-ads-all.mrs
    behavior: domain
    format: mrs
    proxy: ğŸ¯ å…¨çƒç›´è¿
  GEOIP-Private:
    type: http
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/private.mrs
    behavior: ipcidr
    format: mrs
    proxy: ğŸ¯ å…¨çƒç›´è¿
  GEOIP-CN:
    type: http
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geoip/cn.mrs
    behavior: ipcidr
    format: mrs
    proxy: ğŸ¯ å…¨çƒç›´è¿
  GEOSITE-Private:
    type: http
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/private.mrs
    behavior: domain
    format: mrs
    proxy: ğŸ¯ å…¨çƒç›´è¿
  GEOSITE-CN:
    type: http
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/cn.mrs
    behavior: domain
    format: mrs
    proxy: ğŸ¯ å…¨çƒç›´è¿
  geolocation-!cn:
    type: http
    url: https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo/geosite/geolocation-!cn.mrs
    behavior: domain
    format: mrs
    proxy: ğŸ¯ å…¨çƒç›´è¿
proxies:
  - name: HK, Kowloon
    type: ss
    server: 13.112.73.126
    port: 443
    cipher: aes-256-cfb
    password: amazonskr05
  - name: KR, Incheon
    type: ss
    server: 54.179.52.175
    port: 443
    cipher: aes-256-cfb
    password: amazonskr05
  - name: US, Dallas 2
    type: ss
    server: 34.217.15.41
    port: 443
    cipher: aes-256-cfb
    password: amazonskr05
  - name: JP, Osaka
    type: ss
    server: 18.183.170.175
    port: 443
    cipher: aes-256-cfb
    password: amazonskr05
  - name: US, Houston
    type: ss
    server: 54.245.10.2
    port: 443
    cipher: aes-256-cfb
    password: amazonskr05
  - name: JP, Tokyo 2
    type: ss
    server: 43.207.203.164
    port: 443
    cipher: aes-256-cfb
    password: amazonskr05
  - name: HK, Los Angeles
    type: ss
    server: 34.220.128.153
    port: 443
    cipher: aes-256-cfb
    password: amazonskr05
  - name: TW, Taipei
    type: ss
    server: 52.76.22.133
    port: 443
    cipher: aes-256-cfb
    password: amazonskr05
  - name: SG, Singapore
    type: ss
    server: 43.202.67.225
    port: 443
    cipher: aes-256-cfb
    password: amazonskr05
  - name: JP, Tokyo
    type: ss
    server: 43.203.206.73
    port: 443
    cipher: aes-256-cfb
    password: amazonskr05
  - name: CA, Vancouver
    type: ss
    server: 52.37.220.218
    port: 443
    cipher: aes-256-cfb
    password: amazonskr05
  - name: HK, New Territories
    type: ss
    server: 3.36.26.148
    port: 443
    cipher: aes-256-cfb
    password: amazonskr05
proxy-groups:
  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    filter: ""
    exclude-filter: ""
    hidden: false
    icon: ""
    use:
      - ID_zgtbha0a
    proxies:
      - ğŸˆ è‡ªåŠ¨é€‰æ‹©
    disable-udp: false
  - name: ğŸˆ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    filter: ""
    exclude-filter: ""
    hidden: false
    icon: ""
    use:
      - ID_zgtbha0a
    url: https://www.gstatic.com/generate_204
    interval: 300
    tolerance: 150
    lazy: true
    disable-udp: false
  - name: ğŸ¯ å…¨çƒç›´è¿
    type: select
    filter: ""
    exclude-filter: ""
    hidden: false
    icon: ""
    proxies:
      - DIRECT
      - REJECT
    disable-udp: false
  - name: ğŸ›‘ å…¨çƒæ‹¦æˆª
    type: select
    filter: ""
    exclude-filter: ""
    hidden: false
    icon: ""
    proxies:
      - REJECT
      - DIRECT
    disable-udp: false
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    filter: ""
    exclude-filter: ""
    hidden: false
    icon: ""
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
    disable-udp: false
rules:
  - AND,((DST-PORT,443),(NETWORK,udp)),ğŸ›‘ å…¨çƒæ‹¦æˆª
  - RULE-SET,category-ads-all,ğŸ›‘ å…¨çƒæ‹¦æˆª
  - RULE-SET,GEOIP-Private,ğŸ¯ å…¨çƒç›´è¿,no-resolve
  - RULE-SET,GEOIP-CN,ğŸ¯ å…¨çƒç›´è¿,no-resolve
  - RULE-SET,GEOSITE-Private,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,GEOSITE-CN,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,geolocation-!cn,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼
